name: Gateio
# This workflow is triggered on pushes to the repository.
on:
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build:
    name: Gateio tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2

      # - run: python3 gateio/pairs.py -m > gateio/gateio_margin_pairs.txt
      - run: python3 gateio/pairs.py -q BTC > gateio/gateio_BTC_pairs.txt
      - run: python3 gateio/pairs.py -q USDT > gateio/gateio_USDT_pairs.txt
      - run: python3 gateio/pairs.py -q ETH > gateio/gateio_ETH_pairs.txt
      - run: python3 gateio/pairs.py > gateio/gateio_all_pairs.txt
      - run: python3 gateio/pairs.py -f > gateio/gateio_futures.txt
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gateio/
          git diff-index --quiet HEAD || git commit -m "Gateio: automatic update" -a
          git pull --rebase && git push
