name: Okx
# This workflow is triggered on pushes to the repository.
on:
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build:
    name: Okx tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2

      # - run: python3 okx/pairs.py -m -q BTC> okx/okx_BTC_margin.txt
      # - run: python3 okx/pairs.py -m -q USDT> okx/okx_USDT_margin.txt
      # - run: python3 okx/pairs.py -m -q ETH> okx/okx_ETH_margin.txt
      - run: python3 okx/pairs.py -m > okx/okx_margin_pairs.txt
      - run: python3 okx/pairs.py -f > okx/okx_futures.txt
      - run: python3 okx/pairs.py -s > okx/okx_margin_pairs.txt
      - run: python3 okx/pairs.py -q BTC > okx/okx_BTC_pairs.txt
      - run: python3 okx/pairs.py -q USDT > okx/okx_USDT_pairs.txt
      - run: python3 okx/pairs.py -q ETH > okx/okx_ETH_pairs.txt
      - run: python3 okx/pairs.py > okx/okx_all_pairs.txt
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add okx/
          git diff-index --quiet HEAD || git commit -m "Okx: automatic update" -a
          git pull --rebase && git push
